services:
  nginx:
    container_name: "nginx"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports: 
      - "443:443"
    restart:
      always
    env_file:
      - .env
  mariadb:
    container_name: "mariadb"
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    # restart:
    #   always
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
