services:
  nginx:
    container_name: "nginx"
    networks:
      - Inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports: 
      - "443:443"
    restart:
      always
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/html
  mariadb:
    container_name: "mariadb"
    networks:
      - Inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    secrets:
      - db_root_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    restart:
      always
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: "wordpress"
    networks:
      - Inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart:
      always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

networks:
  Inception:

volumes:
  mariadb:
  wordpress:

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
