services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - Inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx/cert:/etc/nginx/cert
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - Inception
    restart: always
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      interval: 5s

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    expose:
      - 9000
    restart: always

networks:
  Inception:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rbardet-/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rbardet-/data/wordpress

