CREATE DATABASE IF NOT EXISTS ${MY_SQL_DBNAME};
CREATE USER IF NOT EXISTS '${MY_SQL_USER}'@'%' IDENTIFIED BY '${DB_ROOT_PASS}';
GRANT ALL PRIVILEGES ON ${MY_SQL_DBNAME}.* TO '${MY_SQL_USER}'@'%';
FLUSH PRIVILEGES;
